const WA_NUMBER="923093113980";
function wa(text){window.open(`https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(text)}`,"_blank")}
function openWhatsAppGeneral(){wa("Assalam-o-Alaikum A&M MART, I would like to know more about your products and ordering process.")}
function vendorWhatsApp(){wa("Assalam-o-Alaikum A&M MART, I am interested in becoming a vendor/seller. Please share the registration process.")}
function productWhatsApp(id){const p=products.find(x=>x.id===id);if(!p)return;wa(`Assalam-o-Alaikum A&M MART, I am interested in: ${p.name} | ${p.category} | ${money(p.price)}. Please confirm availability and delivery.`)}
const categories=[{name:'Electronics',icon:'📺'},{name:'Home Appliances',icon:'🧊'},{name:'Home & Living',icon:'🏠'},{name:'IT Products',icon:'💻'},{name:'Industrial',icon:'🛠️'},{name:'General',icon:'📦'}];
const defaultProducts=[
{id:1,name:'43” Smart LED TV',category:'Electronics',price:42999,stock:8,icon:'📺',vendor:'Demo Seller'},
{id:2,name:'465L Twin Inverter Refrigerator',category:'Home Appliances',price:89999,stock:5,icon:'🧊',vendor:'Demo Seller'},
{id:3,name:'Front Load Washing Machine',category:'Home Appliances',price:64999,stock:6,icon:'🧺',vendor:'Demo Seller'},
{id:4,name:'1.5 Ton Inverter AC',category:'Home Appliances',price:88999,stock:4,icon:'❄️',vendor:'Demo Seller'},
{id:5,name:'Business Laptop 15.6”',category:'IT Products',price:124999,stock:7,icon:'💻',vendor:'Tech Vendor'},
{id:6,name:'Heavy Duty Pallet Rack',category:'Industrial',price:185000,stock:3,icon:'🏗️',vendor:'Industrial Vendor'},
{id:7,name:'Hand Pallet Truck 2.5T',category:'Industrial',price:95000,stock:6,icon:'🛒',vendor:'Industrial Vendor'},
{id:8,name:'Executive Office Chair',category:'Home & Living',price:28999,stock:9,icon:'🪑',vendor:'Office Vendor'}];
let products=JSON.parse(localStorage.getItem('am_products')||'null')||defaultProducts;
let cart=JSON.parse(localStorage.getItem('am_cart')||'[]');
let orders=JSON.parse(localStorage.getItem('am_orders')||'[]');
function save(){localStorage.setItem('am_products',JSON.stringify(products));localStorage.setItem('am_cart',JSON.stringify(cart));localStorage.setItem('am_orders',JSON.stringify(orders));}
function money(n){return 'Rs. '+Number(n||0).toLocaleString('en-PK')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='categories')renderProducts();if(id==='cart')renderCart();if(id==='orders')renderOrders();if(id==='vendor')renderVendor();if(id==='admin')renderAdmin();window.scrollTo({top:0,behavior:'smooth'});}
function renderCategories(){document.getElementById('categoryCards').innerHTML=categories.map(c=>`<div class="category-card" onclick="filterCategory('${c.name}')"><div class="category-icon">${c.icon}</div><b>${c.name}</b><span class="muted">${products.filter(p=>p.category===c.name).length} products</span></div>`).join('');document.getElementById('categoryFilter').innerHTML=['All',...categories.map(c=>c.name)].map(x=>`<option>${x}</option>`).join('');document.getElementById('vpCategory').innerHTML=categories.map(c=>`<option>${c.name}</option>`).join('');}
function card(p){return `<div class="product-card"><div class="product-img">${p.icon||'📦'}</div><div class="product-body"><div class="muted">${p.category}</div><h3>${p.name}</h3><div class="muted">Seller: ${p.vendor||'A&M MART Vendor'}</div><div class="price">${money(p.price)}</div><div class="stock">${p.stock>0?'In Stock':'Out of Stock'}</div><div class="product-actions"><button class="add" onclick="addToCart(${p.id})">Add to Cart</button><button class="buy" onclick="buyNow(${p.id})">Buy Now</button><button class="wa-product" onclick="productWhatsApp(${p.id})">Ask on WhatsApp</button></div></div></div>`}
function renderProducts(){const search=(document.getElementById('searchInput').value||'').toLowerCase();const filter=document.getElementById('categoryFilter')?.value||'All';const list=products.filter(p=>(filter==='All'||p.category===filter)&&(`${p.name} ${p.category}`.toLowerCase().includes(search)));document.getElementById('allProducts').innerHTML=list.map(card).join('')||'<p>No products found.</p>';document.getElementById('featuredProducts').innerHTML=products.slice(0,4).map(card).join('');}
function filterCategory(cat){go('categories');document.getElementById('categoryFilter').value=cat;renderProducts();}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();updateCartCount();toast('Added to cart');}
function buyNow(id){addToCart(id);go('cart')}
function updateCartCount(){document.getElementById('cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0)}
function changeQty(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart();updateCartCount()}
function removeCart(id){cart=cart.filter(x=>x.id!==id);save();renderCart();updateCartCount()}
function renderCart(){const box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return'';return `<div class="cart-row"><div class="cart-thumb">${p.icon||'📦'}</div><div class="grow"><b>${p.name}</b><div class="muted">${money(p.price)} each</div></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div><b>${money(p.price*i.qty)}</b><span class="remove" onclick="removeCart(${p.id})">Remove</span></div>`}).join(''):'<div class="panel">Your cart is empty.</div>';const subtotal=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);const delivery=subtotal?300:0;document.getElementById('cartSubtotal').textContent=money(subtotal);document.getElementById('cartDelivery').textContent=money(delivery);document.getElementById('cartTotal').textContent=money(subtotal+delivery);}

function cartMessage(){if(!cart.length)return "My cart is empty.";const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`${p.name} x ${i.qty} = ${money(p.price*i.qty)}`:""}).filter(Boolean);const subtotal=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);const delivery=subtotal?300:0;return `Assalam-o-Alaikum A&M MART, I would like to order:\n\n${lines.join("\n")}\n\nSubtotal: ${money(subtotal)}\nDelivery: ${money(delivery)}\nTotal: ${money(subtotal+delivery)}`;}
function orderCartOnWhatsApp(){if(!cart.length){toast("Cart is empty");return}wa(cartMessage())}
function checkoutOnWhatsApp(){if(!cart.length){toast("Cart is empty");return}const name=document.getElementById("coName").value.trim();const phone=document.getElementById("coPhone").value.trim();const address=document.getElementById("coAddress").value.trim();if(!name||!phone||!address){toast("Please complete checkout details");return}wa(cartMessage()+`\n\nCustomer: ${name}\nPhone: ${phone}\nAddress: ${address}\nPayment: Cash on Delivery`)}
function placeOrder(){if(!cart.length){toast('Cart is empty');return}const name=document.getElementById('coName').value.trim(),phone=document.getElementById('coPhone').value.trim(),address=document.getElementById('coAddress').value.trim();if(!name||!phone||!address){toast('Please complete checkout details');return}const subtotal=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);orders.unshift({id:'AM'+Date.now().toString().slice(-6),date:new Date().toLocaleString(),name,phone,address,payment:document.getElementById('coPayment').value,items:cart.map(x=>({...x})),total:subtotal+300,status:'Order Placed'});cart=[];save();updateCartCount();toast('Order placed successfully');go('orders');}
function orderHtml(o,admin=false){return `<div class="order-card"><div class="grow"><b>Order #${o.id}</b><div class="muted">${o.date} • ${o.name}</div><div>${o.items.length} item(s) • <b>${money(o.total)}</b></div></div><span class="status">${o.status}</span>${admin?`<select onchange="updateOrderStatus('${o.id}',this.value)"><option>Order Placed</option><option>Confirmed</option><option>Picked by Courier</option><option>Out for Delivery</option><option>Delivered</option></select>`:''}</div>`}
function renderOrders(){document.getElementById('ordersList').innerHTML=orders.length?orders.map(o=>orderHtml(o)).join(''):'<div class="panel">No orders yet.</div>'}
function toggleVendorForm(){document.getElementById('vendorForm').classList.toggle('hidden')}
function addVendorProduct(){const name=document.getElementById('vpName').value.trim(),category=document.getElementById('vpCategory').value,price=Number(document.getElementById('vpPrice').value),stock=Number(document.getElementById('vpStock').value);if(!name||!price){toast('Enter product name and price');return}const icon=categories.find(c=>c.name===category)?.icon||'📦';products.push({id:Date.now(),name,category,price,stock,icon,vendor:'Vendor Demo'});save();renderVendor();renderProducts();toast('Vendor product added');}
function renderVendor(){const vprods=products.filter(p=>p.vendor!=='Demo Seller');document.getElementById('vProducts').textContent=vprods.length;document.getElementById('vOrders').textContent=orders.length;document.getElementById('vPending').textContent=orders.filter(o=>o.status!=='Delivered').length;document.getElementById('vRevenue').textContent=money(orders.reduce((s,o)=>s+o.total,0));document.getElementById('vendorProducts').innerHTML=vprods.length?vprods.map(p=>`<div class="vendor-row"><div class="cart-thumb">${p.icon}</div><div class="grow"><b>${p.name}</b><div class="muted">${p.category} • Stock ${p.stock}</div></div><b>${money(p.price)}</b></div>`).join(''):'<p>No vendor products yet.</p>';}
function updateOrderStatus(id,status){const o=orders.find(x=>x.id===id);if(o){o.status=status;save();renderAdmin();toast('Order status updated')}}
function renderAdmin(){const gmv=orders.reduce((s,o)=>s+o.total,0);document.getElementById('aProducts').textContent=products.length;document.getElementById('aOrders').textContent=orders.length;document.getElementById('aGMV').textContent=money(gmv);document.getElementById('aCommission').textContent=money(Math.round(gmv*.08));document.getElementById('adminOrders').innerHTML=orders.length?orders.map(o=>orderHtml(o,true)).join(''):'<p>No orders yet.</p>';document.querySelectorAll('#adminOrders select').forEach((s,i)=>{if(orders[i])s.value=orders[i].status})}
renderCategories();renderProducts();updateCartCount();
